export const FETCH_NEWS_IDS = 'FETCH_NEWS_IDS';
export const FETCH_NEWS_IDS_SUCCESS = 'FETCH_NEWS_IDS_SUCCESS';
export const FETCH_NEWS_IDS_ERROR = 'FETCH_NEWS_IDS_ERROR';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';
